### ISSUE TITLE
Blog item byline

### ISSUE THREAD

**Issue by KitWallace** [BristolOpenData/BristolOpenData.github.io#15]
Blog items are anonymous at present. I think they need a byline to go in the front matter but what form should this take?

**Comment by jennet** [comment]
You can use the `author` on the post front matter, and this can be shown on the post page where the date is shown.

If we want to show an author on the listings pages, I suggest putting `author_initials` into the front matter, as when I was considering putting that in, inconsistent lengths of text would looked messy on the list page.

**Comment by jennet** [comment]
I've started the docs over on the wiki https://github.com/BristolOpenData/BristolOpenData.github.io/wiki/Blog-Post-Front-Matter
