### ISSUE TITLE
review current posts pre go live

### ISSUE THREAD

**Issue by KitWallace** [BristolOpenData/BristolOpenData.github.io#16]

**Comment by elspeth-b** [comment]
Hi @KitWallace - add me as the assignee :)

**Comment by KitWallace** [comment]
From Elspeth:
ODI Bristol website content: - https://bristolopendata.github.io/odi-fridays-livestreams/ - the 'ODI Bristol eventbrite page' needs to be replaced with 'Bristol Open Data Meetup page

https://bristolopendata.github.io/odi-fridays-livestreams/ - @ODIBristol twitter account and the @BristolOpenData twitter account should be mentioned
https://bristolopendata.github.io/Experiences-with-tree-data/ - wrap text better with photo, looks odd standalone at the top
https://bristolopendata.github.io/Experiences-with-tree-data/ - should Arboretum be capitalised?
General comment - need a method of proofing submissions before publishing on website
https://bristolopendata.github.io/Experiences-with-tree-data/ - have not finished proofing, but need to review thoroughly as looks as though there are missing hyperlinks and the like
Generally content is all fine, don't look to be any mistakes other than those noted above, but some bits need a but of tidying up with spacing and punctuation

**Comment by KitWallace** [comment]
https://bristolopendata.github.io/Experiences-with-tree-data/ 

Not sure how to wrap text around photos in Markup 

Agree Arboretum sb lc
Typos corrected and two missing links added

**Comment by jennet** [comment]
I have changed the eventbrite link on the livestream page to meetup.com - related issue (outside the scope of github? I will add on trello) is to create events on meetup for the livestream events in bristol

**Comment by jennet** [comment]
@elspeth-b I've had a look around the content, made changes (e.g. image wrap where appropriate) and think this can be closed off. Outstanding issue is the feature request for a moderation / drafting of posts, could you create a separate issue for that?
