### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by KitWallace** [BristolOpenData/BristolOpenData.github.io#7]
The domain name for this site will be

http://bristolopendata.org.uk/

Registered with https://www.gandi.net by Gary on 2017-03-09

Credentials for access to gandi.net are only with Gary at present and need to be shared (just in case ...) and for renewal (presumably not automatic)  Is Trello the place for these credentials?

**Comment by bramblefinch** [comment]
The domain was bought on my account, which also has my own domains on it.

The plan is that now John at HBB has our reference number set up, we can get our own gandi account registered to the Gmail email address for bod, and then transfer to domain to this new account.

Trello is not the place to transmit account keys for security reasons. They should be shared in person at a meeting. We can look into proper key storage for the group in future.

**Comment by jwgbradford** [comment]
The domain has been moved to a new Gandi account under HBB. All the Whois info should be pointing at HBB now. Renewals will be through HBB & I'll keep an eye on that (and make sure funds are in place to ensure it happens) as part of supporting tech community.

Think this ticket can be closed?
